version: '3.5'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./certs:/etc/traefik/certs"
    networks:
      - traefik
  whoami:
    container_name: "whoami"
    image: containous/whoami
    networks:
      - traefik
    labels:
      - traefik.http.routers.whoami-https.rule=Host(`whoami.traefik.local`)
      - traefik.http.routers.whoami-https.tls=true
  snowflake:
    container_name: "snowflake"
    image: containous/whoami
    networks:
      - traefik
    labels:
      - traefik.http.routers.snowflake-https.rule=Host(`snowflake.traefik.local`)
      - traefik.http.routers.snowflake-https.tls=true

networks:
  traefik:
    name: "traefik"
