version: '3.5'

services:
  traefik:
    image: traefik:v1.7
    ports:
      - "80:80"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik
  whoami:
    container_name: "whoami"
    image: containous/whoami
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:whoami.traefik.local"


networks:
  traefik:
    name: "traefik"
