## Let's be verbose in our demo example

[global]
  debug = true

[log]
  level = "debug"

[accessLog]


## HTTPS endpoints

[entryPoints]
  [entryPoints.https]
    address = ":443"


## TLS
[providers.file]
watch=true

[[tls]]
  [tls.certificate]
    certFile = "/etc/traefik/certs/whoami.crt"
    keyFile = "/etc/traefik/certs/whoami.key"

[[tls]]
  [tls.certificate]
    certFile = "/etc/traefik/certs/snowflake.crt"
    keyFile = "/etc/traefik/certs/snowflake.key"

[tlsOptions]
  [tlsOptions.default]
    sniStrict = true


## Docker auto-discovery

[providers.docker]
  domain = "traefik.local"
  network = "traefik"
