## Let's be verbose in our demo example

logLevel = "DEBUG"
[accessLog]


## HTTPS termination in traefic

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      sniStrict = true
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/whoami.crt"
      keyFile = "/etc/traefik/certs/whoami.key"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/snowflake.crt"
      keyFile = "/etc/traefik/certs/snowflake.key"


## Docker auto-discovery

[docker]
domain = "traefik.local"
watch = true
network = "traefik"
